### ISSUE TITLE
Add a settings page

### ISSUE THREAD

**Issue by setoy** [Top-Cat/UnofficialSteamAuthenticator#11]
Settings to control:

- [ ] Enable / disable auto login to chat
- [ ] Default chat status (Online / Busy / Away)

**Comment by adrie-dh** [comment]
This seems like the place to ask:
Setting your i18n preference of language.
(ie: it decided to give me german language, as a dutch person, and no way to change it to english)

**Comment by Top-Cat** [comment]
It's done automatically based on device language I think.

What language is set under settings > language?
And what version of the app is installed?

**Comment by adrie-dh** [comment]
> What language is set under settings > language?
"Nederlands", which is dutch for Dutch.

> And what version of the app is installed?
It updated this morning, version 1.3.0.
Since it updated, the language shown to me now is English.
(Which is fine by me, but it's a bit odd considering the phone is set to dutch)

> It's done automatically based on device language I think.
I'm guessing a setting might be helpful for at least the users using a language not supported by this app, or an oddball like me who just likes app like these in it's native English :)

**Comment by Top-Cat** [comment]
It's back in english because of witchcraft.
Your translations were added after the update was built though and will be included in the next release.

I will look into an option to manual set the app language though.

**Comment by Top-Cat** [comment]
The page has been added, chat specific options really come under #10
